# EXCEPTION CASE 27_2
try:
    print("try scope")
except:
    print("exception")
else:
    print("no exception found")
finally:
    raise
    continue
    print("finally....")
