# EXCEPTION CASE 21
try:
    raise
except:
    print("exception")
else:
    break
    print("no exception found")
