# EXCEPTION CASE 27_3
try:
    print("try scope")
except:
    print("exception")
else:
    print("no exception found")
finally:
    continue
    print("finally....")
