# EXCEPTION CASE 0
try:
    print("try scope")

